spring.application.name=ecommerce

server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://dpg-d8ui2me8bjmc73dsld7g-a:5432/e_com_ojo5
spring.datasource.username=e_com_ojo5_user
spring.datasource.password=eRjzL7wMOk9Y5uAYWmhLs4RC0SZtxccx
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
